# DOCKERFILE for Peer.

FROM loop-base:latest
MAINTAINER TheLoop Dev Team <dev@theloop.co.kr>

# Create known_hosts
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan repo.theloop.co.kr >> /root/.ssh/known_hosts
ADD requirements.txt .
RUN pip3 install -r requirements.txt

# COPY LOOPCHAIN VERSION
COPY ./deploy/LOOPCHAIN_VERSION LOOPCHAIN_VERSION

# COPY peer project.
RUN mkdir ./loopchain ./score ./.storage ./resources

COPY ./loopchain/ ./loopchain/
COPY ./resources/default_certs ./resources/default_certs
COPY ./resources/default_pki ./resources/default_pki

# COPY SCORE
COPY ./score/loopchain_default.zip ./score/loopchain_default.zip
COPY ./peer.py ./
COPY ./loopchain.py ./
COPY ./rest_proxy.py ./


# Start service
# ENTRYPOINT or CMD
# CMD python3 loopchain.py peer

# Expose port.
#  for gRPC
EXPOSE 7100
EXPOSE 7101
EXPOSE 7102
EXPOSE 9000